server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/friend_finder?useUnicode=true
    username: root
    password: root
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/changelog.xml


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  mail:
    host: smtp.gmail.com
    username: finderfriend2023@gmail.com
    password: dlvwnndbnoxemfwr
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: YmJieXZmaHRkZHZoO2lvdWJ2NHNhemF6d2prJ2xbcGk4eWRlc3J0Zmhsb2tsW3BwbHBvb2ZnaGdkaHNnd3NlZnc=
  expiration: 600000

#Post path
post:
  upload:
    image:
      path: D:/friend-finder-modular/images/

  video:
    upload:
      image:
        path: D:/friend-finder-modular/images/


#User profile
user:
  profile:
    picture:
      path: D:/friend-finder-modular/images/
    background-picture:
      path: D:/friend-finder-modular/images/

site:
  url: http://localhost:8081


